baseURL: https://chrisk91.me
disablePathToLower: true
languageCode: en-us
title: ChrisK91.me
theme: chrisk91-theme
disqusShortname: http-chrisk91-me
googleAnalytics: "G-30MHG4HNXJ"

menu:
  main:
  - name: EKG visualizer
    url: https://chrisk91.me/ekgApp/
    weight: 0

params:
  otherSites:
    - url: https://christian-j.com/
      title: christian-j.com
      description: My second website where I write about photography-related topics. These topics are more separate than the technical posts on this page, so I wanted to group them a bit more.
    - url: https://medist.org/
      title: medist.org
      description: Checklists and calculators related to medicine can be found here. In a sense, these are stuff I collect during work, and that I write and publish to the web using static site generation.
      