baseURL: https://chrisk91.me
disablePathToLower: true
locale: en-us
title: ChrisK91.me
theme: chrisk91-theme
disqusShortname: http-chrisk91-me
googleAnalytics: "G-30MHG4HNXJ"
summaryLength: 100

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  tools:
  - name: EKG visualizer
    url: https://chrisk91.me/ekgApp/
    weight: 0

params:
  otherSites:
    - url: https://christian-j.com/
      title: christian-j.com
      description: My second website where I write about photography-related topics. These topics are more separate than the technical posts on this page, so I wanted to group them a bit more.
    - url: https://medist.org/
      title: medist.org
      description: Checklists and calculators related to medicine can be found here. In a sense, these are stuff I collect during work, and that I write and publish to the web using static site generation.
      
security:
  allowContent:
  - '! ^text/html$'
  enableInlineShortcodes: false
  exec:
    allow:
    - ^(dart-)?sass(-embedded)?$
    - ^go$
    - ^git$
    - ^node$
    - ^postcss$
    - ^tailwindcss$
    - ^tailwind$
    osEnv:
    - '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$'
  funcs:
    getenv:
    - ^HUGO_
    - ^CI$
  http:
    mediaTypes: null
    methods:
    - (?i)GET|POST
    urls:
    - (?i)^https?://[a-z0-9]
    - '! ^https?://\d+\.'
    - '! (?i)localhost'
    - '! (?i)^https?://[^/?#]*@'
  node:
    permissions:
      allowAddons:
      - tailwindcss
      allowChildProcess:
      - tailwindcss
      allowRead:
      - .
      - "*"
      allowWorker:
      - tailwindcss
      allowWrite: []
      disable: false